/**
 * Writing and reading overlays.
 *
 * This module holds the only INSERT into `overlays` in the codebase, and it
 * contains no UPDATE and no DELETE at all — not as a matter of style but because
 * the doctrine scan in the test suite fails the build if one appears. A
 * correction adds a layer; it never overwrites.
 */

import { newId, now, type Db } from '../db/index.js'
import { findCorrectableField, forbiddenField } from './fields.js'
import {
  entityKey, resolveState, toOverlay, VALUE_KINDS,
  type EntityState, type Overlay, type OverlayRow,
} from './model.js'

/** A refusal the operator can act on, not a stack trace. */
export class OverlayRefused extends Error {
  constructor(
    message: string,
    readonly code: string,
  ) {
    super(message)
    this.name = 'OverlayRefused'
  }
}

export interface WriteOverlayArgs {
  db: Db
  propertyId: string
  visitId: string
  kind: string
  targetKind: string
  targetId: string
  field?: string | null
  newValue?: unknown
  reason?: string | null
  /** Required for undo. Otherwise resolved automatically — see below. */
  supersedesId?: string | null
  /** Required for accept: the proposal this act is answering. */
  generationId?: string | null
  actor?: string
  actorContext?: string
}

const TARGET_EXISTS: Record<string, (db: Db, visitId: string, targetId: string) => boolean> = {
  pin: (db, v, t) => exists(db, `SELECT 1 FROM pins WHERE visit_id = ? AND pin_id = ?`, v, t),
  zone: (db, v, t) => exists(db, `SELECT 1 FROM zones WHERE visit_id = ? AND zone_id = ?`, v, t),
  media: (db, v, t) => exists(db, `SELECT 1 FROM media WHERE visit_id = ? AND media_id = ?`, v, t),
}

const exists = (db: Db, sql: string, ...args: unknown[]): boolean => db.prepare(sql).get(...args) !== undefined

/** What a `place` overlay carries. */
export interface PlaceValue {
  canvasId: string
  /** Normalized 0–1 against the canvas image, exactly like a field anchor. */
  x: number
  y: number
  /** What the position was read from. Required — see the note in writeOverlay. */
  evidence?: { kind: string; id: string }
}

/**
 * Is this evidence actually in hand for this pin?
 *
 * "In hand" means attached to the pin itself, or owned by the room the pin is
 * in — a photo of the wall the pin is on is the ordinary case, and it belongs
 * to the zone rather than to the pin. Anything further away is not something
 * you can read a position off, and a placement claiming it would be recall
 * wearing evidence's clothes.
 */
function evidenceInHand(
  db: Db,
  visitId: string,
  pinId: string,
  evidence: { kind: string; id: string },
): boolean {
  const zoneId = (
    db
      .prepare(
        `SELECT p.zone_id FROM pins p JOIN imports i ON i.id = p.import_id
          WHERE p.visit_id = ? AND p.pin_id = ? ORDER BY i.imported_at DESC LIMIT 1`,
      )
      .get(visitId, pinId) as { zone_id: string | null } | undefined
  )?.zone_id ?? null

  if (evidence.kind === 'media') {
    return exists(
      db,
      `SELECT 1 FROM media m JOIN imports i ON i.id = m.import_id
        WHERE i.visit_id = ? AND m.media_id = ? AND (m.owner_pin_id = ? OR m.owner_zone_id IS ?)`,
      visitId, evidence.id, pinId, zoneId,
    )
  }
  if (evidence.kind === 'note') {
    return exists(
      db,
      `SELECT 1 FROM notes n JOIN imports i ON i.id = n.import_id
        WHERE i.visit_id = ? AND n.note_id = ? AND n.target_id IN (?, ?)`,
      visitId, evidence.id, pinId, zoneId,
    )
  }
  if (evidence.kind === 'chat') {
    return exists(
      db,
      `SELECT 1 FROM chat_threads t JOIN imports i ON i.id = t.import_id
        WHERE i.visit_id = ? AND t.thread_id = ? AND t.target_id IN (?, ?)`,
      visitId, evidence.id, pinId, zoneId,
    )
  }
  // A kind this builder has not met is not silently accepted here: unlike a
  // vocabulary word arriving from the field app, this one is generated by our
  // own screen, and accepting it would mean accepting an unverifiable binding.
  return false
}

/**
 * Write one overlay.
 *
 * The supersession rule, which is the subtle part: an overlay replaces the
 * latest LIVE overlay of the SAME KIND on the SAME FIELD of the same entity, and
 * nothing else. Correcting a pin's type twice supersedes; confirming a pin that
 * is already flagged does not, because "the label reads what the field says it
 * reads" and "somebody should look at this again" are both true at once and
 * collapsing them would lose a fact the pass exists to collect.
 */
export function writeOverlay(args: WriteOverlayArgs): Overlay {
  const { db, propertyId, visitId } = args
  const kind = String(args.kind ?? '').trim()
  const targetKind = String(args.targetKind ?? '').trim()
  const targetId = String(args.targetId ?? '').trim()
  const field = args.field ? String(args.field).trim() : null
  const reason = args.reason ? String(args.reason).trim() : null

  if (!kind) throw new OverlayRefused('An overlay needs a kind.', 'overlay.no-kind')
  if (!targetKind || !targetId) {
    throw new OverlayRefused('An overlay needs something to point at.', 'overlay.no-target')
  }

  // Doctrine gate, before anything else touches the database.
  if (field) {
    const bad = forbiddenField(field)
    if (bad) {
      throw new OverlayRefused(
        `An overlay cannot record "${field}". The concierge identifies and documents; licensed specialists ` +
          `assess. A judgement about ${bad} belongs in a triggered flag recommending a specialist, not in a ` +
          `field on the record.`,
        'overlay.forbidden-field',
      )
    }
  }

  const visit = db.prepare('SELECT id, property_id FROM visits WHERE id = ?').get(visitId) as
    | { id: string; property_id: string }
    | undefined
  if (!visit) throw new OverlayRefused('No such visit.', 'overlay.no-visit')
  if (visit.property_id !== propertyId) {
    throw new OverlayRefused('That visit belongs to a different property.', 'overlay.property-mismatch')
  }

  let priorValue: unknown = null
  let supersedesId = args.supersedesId ?? null
  let effectiveTargetKind = targetKind
  let effectiveTargetId = targetId

  // ------------------------------------------------------------------- undo
  if (kind === 'undo') {
    if (!supersedesId) {
      throw new OverlayRefused('An undo has to say what it is undoing.', 'overlay.undo-no-target')
    }
    const target = readOne(db, supersedesId)
    if (!target) throw new OverlayRefused('That decision is not in the record.', 'overlay.undo-unknown')
    if (target.visitId !== visitId) {
      throw new OverlayRefused('That decision belongs to a different visit.', 'overlay.undo-other-visit')
    }
    if (isSuperseded(db, supersedesId)) {
      throw new OverlayRefused('That decision has already been taken back.', 'overlay.already-superseded')
    }
    // The undo points where its target pointed, so the entity's trail stays in
    // one place instead of the retraction filing itself somewhere else.
    effectiveTargetKind = target.targetKind
    effectiveTargetId = target.targetId
    return insert(db, {
      propertyId,
      visitId,
      kind,
      targetKind: effectiveTargetKind,
      targetId: effectiveTargetId,
      field: target.field,
      priorValue: target.newValue,
      newValue: null,
      reason,
      supersedesId,
      actor: args.actor ?? 'concierge',
      actorContext: args.actorContext ?? 'desk',
    })
  }

  // --------------------------------------------------- the target must be real
  const check = TARGET_EXISTS[targetKind]
  if (check && !check(db, visitId, targetId)) {
    throw new OverlayRefused(
      `This visit has no ${targetKind} ${targetId}. An overlay pointing at nothing would be a decision about ` +
        `nothing, and would never surface again.`,
      'overlay.unknown-target',
    )
  }

  // ---------------------------------------------------------------- per-kind
  if (kind === 'correct') {
    if (!field) throw new OverlayRefused('A correction has to say which value it changed.', 'overlay.no-field')
    const spec = findCorrectableField(targetKind, field)
    if (!spec) {
      // A whitelist, not a blacklist. This is also what keeps the desk on the
      // right side of the field line (spec §2): there is no correctable field
      // for an anchor's coordinates or a measurement, so neither can be typed
      // in at the desk however the request is phrased.
      throw new OverlayRefused(
        `"${field}" is not something the desk can correct on a ${targetKind}. Correcting a reading of evidence ` +
          `already captured is desk work; adding new evidence or spatial data is field work.`,
        'overlay.uncorrectable-field',
      )
    }
    if (args.newValue === undefined) {
      throw new OverlayRefused('A correction has to say what the value should be.', 'overlay.no-new-value')
    }

    // The value being replaced is whatever is effective RIGHT NOW: the latest
    // live correction if there is one, otherwise what the field captured. That
    // makes a chain of corrections read continuously instead of every link
    // claiming the original as its "before".
    // If the slot's live occupant is an UNDO, the earlier correction has been
    // withdrawn and the value in force is the field's own again — so the prior
    // value comes from storage, not from the undo (whose newValue is null).
    // Recording null as the "before" would claim the field never typed one.
    const live = liveSlot(db, visitId, targetKind, targetId, VALUE_KINDS, field)
    priorValue = live && VALUE_KINDS.includes(live.kind as (typeof VALUE_KINDS)[number])
      ? live.newValue
      : spec.read(db, visitId, targetId)
    supersedesId = supersedesId ?? live?.id ?? null
  } else if (kind === 'accept') {
    // ------------------------------------------------- accepting a proposal
    //
    // Spec §2. An AI value is never the current value until a human accepts it,
    // and this is the only act that makes one current. The two value columns
    // carry a specific meaning here: prior is what the model proposed, new is
    // what the human accepted. Identical means accepted as-is; different means
    // edited, and that difference IS the accuracy record — "how often is the
    // model right" becomes a query instead of a metric somebody maintains.
    //
    // Signing is not certification. CLAUDE.md §6: it means "I observed this,
    // and this description matches what I saw". Accepting a serial is the same
    // claim as confirming a label — which is why it is the same key on the
    // screen and a decision kind here.
    if (!field) throw new OverlayRefused('An acceptance has to say which value it sets.', 'overlay.no-field')
    if (!args.generationId) {
      throw new OverlayRefused(
        'An acceptance has to say which proposal it is answering.',
        'overlay.accept-no-generation',
      )
    }
    if (args.newValue === undefined) {
      throw new OverlayRefused('An acceptance has to say what the value is.', 'overlay.no-new-value')
    }

    // The same whitelist a correction uses. Acceptance sets the same value by a
    // different route, so it must not become a way around the field line — the
    // desk cannot type an anchor coordinate, and it cannot accept one either.
    if (!findCorrectableField(targetKind, field)) {
      throw new OverlayRefused(
        `"${field}" is not something that can be set on a ${targetKind} from the desk.`,
        'overlay.uncorrectable-field',
      )
    }

    const gen = db
      .prepare('SELECT id, visit_id, task, target_kind, target_id, output, abstained, human_decision FROM ai_generations WHERE id = ?')
      .get(args.generationId) as
      | { id: string; visit_id: string | null; task: string; target_kind: string | null
          target_id: string | null; output: string | null; abstained: number; human_decision: string }
      | undefined
    if (!gen) throw new OverlayRefused('That proposal is not in the record.', 'overlay.accept-unknown-generation')
    if (gen.visit_id !== visitId) {
      throw new OverlayRefused('That proposal belongs to a different visit.', 'overlay.accept-other-visit')
    }
    if (gen.abstained === 1) {
      // Abstention is a success, not a value. There is nothing to accept, and
      // accepting one would manufacture a reading the model explicitly declined
      // to make — the exact laundering doctrine 2 forbids.
      throw new OverlayRefused(
        'That proposal abstained — there is nothing to accept. Type the value yourself, or carry it to the next visit.',
        'overlay.accept-abstained',
      )
    }
    if (gen.human_decision !== 'pending') {
      throw new OverlayRefused(
        `That proposal was already ${gen.human_decision}.`,
        'overlay.accept-already-decided',
      )
    }

    priorValue = proposedValue(gen.output, field)
    supersedesId = supersedesId ?? liveSlot(db, visitId, targetKind, targetId, VALUE_KINDS, field)?.id ?? null
  } else if (kind === 'flag') {
    if (!reason) {
      // Spec §3: flag "carries a short reason". A flag with no reason is a
      // sticky note with nothing written on it — the next person cannot act on
      // it and will not know what caught someone's eye.
      throw new OverlayRefused('A flag needs a short reason.', 'overlay.flag-no-reason')
    }
    supersedesId = supersedesId ?? liveSlot(db, visitId, targetKind, targetId, 'flag', null)?.id ?? null
  } else if (kind === 'place') {
    // -------------------------------------------------- placing an anchor
    //
    // Spec §2 (revised): placing and moving anchors at the desk IS allowed. The
    // earlier rule blocked it on the grounds that the builder was not there,
    // which holds for the claim but not for the work — the requirement is that
    // desk placement never be INDISTINGUISHABLE from field placement, not that
    // it be prevented. Leaving a pin in the wrong room for a month because of a
    // rule is the wrong trade.
    //
    // So it is an overlay, the `anchors` table is untouched, and the record
    // says where the position came from. Increment 4's session plan carries it
    // into the next visit flagged confirm-on-site, where standing in front of
    // it promotes it to field-observed.
    if (targetKind !== 'pin') {
      throw new OverlayRefused('Only a pin can be placed on a canvas.', 'overlay.place-wrong-target')
    }
    const v = args.newValue as PlaceValue | undefined
    if (!v || typeof v.x !== 'number' || typeof v.y !== 'number' || !v.canvasId) {
      throw new OverlayRefused('A placement needs a canvas and a position on it.', 'overlay.place-no-position')
    }
    if (!(v.x >= 0 && v.x <= 1 && v.y >= 0 && v.y <= 1)) {
      // Anchors are normalized 0–1 against the canvas image. Anything else is a
      // marker somewhere off the photograph.
      throw new OverlayRefused(
        'A position on a canvas is two numbers between 0 and 1.',
        'overlay.place-out-of-bounds',
      )
    }
    if (!exists(db, 'SELECT 1 FROM canvases WHERE import_id IN (SELECT id FROM imports WHERE visit_id = ?) AND canvas_id = ?', visitId, v.canvasId)) {
      throw new OverlayRefused('This visit has no such canvas.', 'overlay.place-unknown-canvas')
    }

    // THE GOVERNING LINE IS EVIDENCE VERSUS RECALL, not desk versus field.
    //
    // Placing an unanchored pin whose photo is on screen is grounded — you can
    // see the thing. Placing one from a memory of where the shutoff was is not,
    // and must not become a record; it belongs in the next visit's carried
    // items, pinned by somebody standing there. `evidence` is how the software
    // can tell those apart, so it is required and must resolve.
    if (!v.evidence?.kind || !v.evidence?.id) {
      throw new OverlayRefused(
        'A placement has to point at the evidence it was read from — the photo, note or thread that shows ' +
          'where this is. Something remembered rather than seen belongs in the next visit, not in the record.',
        'overlay.place-no-evidence',
      )
    }
    if (!evidenceInHand(db, visitId, targetId, v.evidence)) {
      throw new OverlayRefused(
        'That evidence is not attached to this pin or its room in this visit, so it cannot be what the ' +
          'position was read from.',
        'overlay.place-evidence-not-in-hand',
      )
    }

    // The prior position: a live desk placement if there is one, otherwise
    // whatever the field anchored. Null when the pin was never placed at all,
    // which is a different fact from being moved and reads that way in the trail.
    const live = liveSlot(db, visitId, targetKind, targetId, 'place', null)
    priorValue =
      live?.kind === 'place'
        ? live.newValue
        : (db
            .prepare(
              `SELECT a.anchor_id AS anchorId, a.canvas_id AS canvasId, a.x, a.y
                 FROM anchors a JOIN imports i ON i.id = a.import_id
                WHERE i.visit_id = ? AND a.pin_id = ? ORDER BY i.imported_at DESC LIMIT 1`,
            )
            .get(visitId, targetId) ?? null)
    supersedesId = supersedesId ?? live?.id ?? null
  } else if (kind === 'assign') {
    const v = args.newValue as { toKind?: string; toId?: string } | undefined
    if (!v?.toKind || !v?.toId) {
      throw new OverlayRefused('An assignment has to say what it is attaching to.', 'overlay.assign-no-destination')
    }
    const destCheck = TARGET_EXISTS[v.toKind]
    if (destCheck && !destCheck(db, visitId, v.toId)) {
      throw new OverlayRefused(`This visit has no ${v.toKind} ${v.toId}.`, 'overlay.assign-unknown-destination')
    }
    supersedesId = supersedesId ?? liveSlot(db, visitId, targetKind, targetId, 'assign', null)?.id ?? null
  } else {
    // confirm, memory, and anything a later increment invents.
    supersedesId = supersedesId ?? liveSlot(db, visitId, targetKind, targetId, kind, field)?.id ?? null
  }

  if (supersedesId && isSuperseded(db, supersedesId)) {
    throw new OverlayRefused('That decision has already been replaced.', 'overlay.already-superseded')
  }

  return insert(db, {
    propertyId,
    visitId,
    kind,
    targetKind,
    targetId,
    field,
    priorValue,
    newValue: args.newValue ?? null,
    reason,
    supersedesId,
    actor: args.actor ?? 'concierge',
    actorContext: args.actorContext ?? 'desk',
    generationId: args.generationId ?? null,
  })
}

interface InsertArgs {
  propertyId: string
  visitId: string
  kind: string
  targetKind: string
  targetId: string
  field: string | null
  priorValue: unknown
  newValue: unknown
  reason: string | null
  supersedesId: string | null
  actor: string
  actorContext: string
  generationId?: string | null
}

const jsonOrNull = (v: unknown): string | null => (v === undefined || v === null ? null : JSON.stringify(v))

/**
 * What the model proposed for one field.
 *
 * Returns null when the output has no opinion about it — an extraction that
 * read a model number and left the serial `unknown` proposed nothing for the
 * serial, and recording `"unknown"` as the prior value would turn a declined
 * reading into a wrong one in the accuracy figures.
 */
function proposedValue(output: string | null, field: string): unknown {
  if (!output) return null
  let parsed: unknown
  try {
    parsed = JSON.parse(output)
  } catch {
    return null
  }
  if (typeof parsed !== 'object' || parsed === null) return null
  const fields = (parsed as Record<string, unknown>).fields
  const bag = (typeof fields === 'object' && fields !== null ? fields : parsed) as Record<string, unknown>
  const v = bag[field]
  return v === undefined || v === 'unknown' ? null : v
}

function insert(db: Db, a: InsertArgs): Overlay {
  const id = newId()
  // seq and the row are assigned together so two acts inside one millisecond
  // still come out in the order they were made.
  const next = db.transaction((): void => {
    const { seq } = db
      .prepare('SELECT COALESCE(MAX(seq), 0) + 1 AS seq FROM overlays WHERE visit_id = ?')
      .get(a.visitId) as { seq: number }
    insertRow(db, id, seq, a)
  })
  next()
  return readOne(db, id)!
}

function insertRow(db: Db, id: string, seq: number, a: InsertArgs): void {
  db.prepare(
    `INSERT INTO overlays
       (id, property_id, visit_id, seq, kind, target_kind, target_id, field, prior_value, new_value,
        reason, supersedes_id, actor, actor_context, generation_id, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  ).run(
    id,
    a.propertyId,
    a.visitId,
    seq,
    a.kind,
    a.targetKind,
    a.targetId,
    a.field,
    jsonOrNull(a.priorValue),
    jsonOrNull(a.newValue),
    a.reason,
    a.supersedesId,
    a.actor,
    a.actorContext,
    a.generationId ?? null,
    now(),
  )
}

// -------------------------------------------------------------------- reading

export function readOne(db: Db, id: string): Overlay | undefined {
  const row = db.prepare('SELECT * FROM overlays WHERE id = ?').get(id) as OverlayRow | undefined
  return row ? toOverlay(row) : undefined
}

export const readVisitOverlays = (db: Db, visitId: string): Overlay[] =>
  (db.prepare('SELECT * FROM overlays WHERE visit_id = ? ORDER BY seq').all(visitId) as OverlayRow[]).map(
    toOverlay,
  )

const isSuperseded = (db: Db, id: string): boolean =>
  exists(db, 'SELECT 1 FROM overlays WHERE supersedes_id = ?', id)

/**
 * Whatever live overlay currently occupies one slot on an entity — where a
 * "slot" is one kind on one field.
 *
 * The second half of the WHERE clause is the part that matters. A live `undo`
 * that retracted a confirm is still sitting in the confirm slot: nothing has
 * replaced the decision, it has only been taken back. So confirming again must
 * supersede that undo rather than land beside it, and the trail then reads
 * "confirmed → unconfirmed → reconfirmed" instead of "confirmed → unconfirmed →
 * confirmed", which is the sentence spec §3 actually asks for.
 *
 * Getting this wrong is invisible in a unit test that passes supersedesId by
 * hand and obvious the first time somebody presses `c`, `u`, `c` on a real
 * screen — which is how it was found.
 */
function liveSlot(
  db: Db,
  visitId: string,
  targetKind: string,
  targetId: string,
  kind: string | readonly string[],
  field: string | null,
): Overlay | undefined {
  // A slot can be held by more than one kind. `correct` and `accept` share one,
  // because both answer "what does this field say now" — see VALUE_KINDS. A
  // correction must therefore supersede an earlier acceptance and vice versa,
  // or the pin would carry two live answers with nothing to choose between them.
  const kinds = typeof kind === 'string' ? [kind] : [...kind]
  const marks = kinds.map(() => '?').join(', ')
  const rows = db
    .prepare(
      `SELECT o.* FROM overlays o
        WHERE o.visit_id = ? AND o.target_kind = ? AND o.target_id = ?
          AND (
            (o.kind IN (${marks}) AND o.field IS ?)
            OR (o.kind = 'undo' AND EXISTS (
                  SELECT 1 FROM overlays t
                   WHERE t.id = o.supersedes_id AND t.kind IN (${marks}) AND t.field IS ?))
          )
          AND NOT EXISTS (SELECT 1 FROM overlays s WHERE s.supersedes_id = o.id)
        ORDER BY o.seq DESC LIMIT 1`,
    )
    .all(visitId, targetKind, targetId, ...kinds, field, ...kinds, field) as OverlayRow[]
  return rows[0] ? toOverlay(rows[0]) : undefined
}

/** Every entity the desk has touched in this visit, with its current state. */
export const visitState = (db: Db, visitId: string): Map<string, EntityState> =>
  resolveState(readVisitOverlays(db, visitId))

export const stateFor = (
  states: Map<string, EntityState>,
  targetKind: string,
  targetId: string,
): EntityState | undefined => states.get(entityKey(targetKind, targetId))

/**
 * The most recent live act in this visit — what the `u` keystroke takes back.
 *
 * Spec §3: "Undo must be one keystroke and instantly available — at this pace
 * mis-taps are certain, and if undo is awkward people slow down to avoid needing
 * it." So the keystroke needs no argument: it undoes the last thing done, which
 * is what a person means by undo.
 */
export function latestLiveDecision(db: Db, visitId: string): Overlay | undefined {
  const rows = db
    .prepare(
      `SELECT o.* FROM overlays o
        WHERE o.visit_id = ? AND o.kind != 'undo'
          AND NOT EXISTS (SELECT 1 FROM overlays s WHERE s.supersedes_id = o.id)
        ORDER BY o.seq DESC LIMIT 1`,
    )
    .all(visitId) as OverlayRow[]
  return rows[0] ? toOverlay(rows[0]) : undefined
}
